### ISSUE TITLE
这么66

### ISSUE THREAD

**Issue by Jiiiiiin** [hookszhang/vue-cli-plugin-vux#1]
👍

**Comment by co-kevin** [comment]
<img width="94" alt="screen shot 2018-09-05 at 10 17 34 am" src="https://user-images.githubusercontent.com/14038071/45067254-f264c800-b0f4-11e8-8dfb-c06c40ea18a4.png">

**Comment by Jiiiiiin** [comment]
加油就靠你了(*￣m￣) vux作者怕是休产假了*罒▽罒*

**Comment by Jiiiiiin** [comment]
加油就靠你了(*￣m￣) vux作者怕是休产假了*罒▽罒*
