### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Versus2017** [hookszhang/vue-cli-plugin-vux#2]
I'm not sure how to use it correctly? can you show me specific usage steps?

**Comment by co-kevin** [comment]
### Create a Vue Project use Vue CLI3

First you should [install Vue CLI33](https://cli.vuejs.org/guide/installation.html) cmd:

```
npm install -g @vue/cli
# OR
yarn global add @vue/cli
```

[Create a Vue project](https://cli.vuejs.org/guide/creating-a-project.html#vue-create) use Vue CLI3

```
vue create hello-world
```

### Usage

Now add [vux](https://vux.li/) to project

```
cd hello-world
vue add vux
```
