### ISSUE TITLE
TypeScript的时候编译错误

### ISSUE THREAD

**Issue by Castleeee** [hookszhang/vue-cli-plugin-vux#7]
错误信息如下
======== vux-loader: duplicate-style start~  ========
Starting to optimize CSS...
======== vux-loader: duplicate-style done!   ========

 98% after emitting CopyPlugin
 ERROR  Failed to compile with 1 errors19:48:03

 error  in ./src/views/Home.vue

Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for D:\COD\html\vux3\src\views\Home.vue.
    at makeSourceMapAndFinish (D:\COD\html\vux3\node_modules\ts-loader\dist\index.js:78:15)
    at successLoader (D:\COD\html\vux3\node_modules\ts-loader\dist\index.js:68:9)
    at Object.loader (D:\COD\html\vux3\node_modules\ts-loader\dist\index.js:22:12)

 @ ./src/views/Home.vue 3:0-152 3:0-152 4:0-165 17:2-16
 @ ./src/router.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://172.26.208.177:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

No type errors found
Version: typescript 3.3.3333
Time: 12298ms

node 10.13.0
npm 6.4.1
vue 3.5.0
vue/cli3.0
新建了使用typescript的项目，bable，eslint，没有单元测试，vuex，vuerouter。
直接运行vue add vux安装成功，无法通过
不使用TS报错如下
 98% after emitting CopyPlugin
 ERROR  Failed to compile with 2 errors20:21:07

This dependency was not found:

* vux/undefined in ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/Home.vue, ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/Home.vue

To install it, you can run: npm install --save vux/undefined
重新安装vux，单独安装这个undefined都无效。

**Comment by Castleeee** [comment]
额，js的没有问题，是我Header拼错了。。。。TS还会有问题。
虽然有问题但是不紧急，因为js其实够用。
最后感谢作者解决了困扰我两天的东西

**Comment by co-kevin** [comment]
TypeScript 是因为 VUX 本身不支持。

https://doc.vux.li/zh-CN/development/typescript.html

> TypeScript 支持
> 即将支持
